name: Telegram PR Notification

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - closed  # To handle PR merges

jobs:
  notify_on_open:
    if: github.event.action == 'opened' || github.event.action == 'synchronize'
    runs-on: ubuntu-latest
    steps:
    - name: Send Telegram Notification for Opened PR
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: |
        PR_AUTHOR="${{ github.event.pull_request.user.login }}"
        PR_URL="${{ github.event.pull_request.html_url }}"
        curl -s -X POST https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendMessage \
        -d chat_id=$TELEGRAM_CHAT_ID \
        -d text="New pull request opened by $PR_AUTHOR: $PR_URL"

  notify_on_merge:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - name: Send Telegram Notification for Merged PR
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: |
        PR_AUTHOR="${{ github.event.pull_request.user.login }}"
        MERGER="${{ github.actor }}"
        PR_URL="${{ github.event.pull_request.html_url }}"
        curl -s -X POST https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendMessage \
        -d chat_id=$TELEGRAM_CHAT_ID \
        -d text="Pull request by $PR_AUTHOR merged into main by $MERGER: $PR_URL 🎉"
